from pydantic import BaseModel, Field


class MedicalQuery(BaseModel):
    """Request model for medical questions"""
    question: str = Field(..., example="What is acne?")


class MedicalAnswer(BaseModel):
    """Response model for medical answers"""
    answer: str = Field(..., description="Medical response generated by LLM")
